Ban user on death updates
Kathund/kath pull request #10
Opened 2023-05-29 16:33 UTC by Zickles

2023-05-29 16:34 UTC, Zickles commented
# Todo

- [ test ]

2023-05-30 04:53 UTC, Kathund requested changes
Add 7d 14d 180d ban length to the options of the ban

2023-06-01 05:46 UTC, Kathund commented
@Zickles is this ready yet

2023-06-01 05:47 UTC, Kathund approved these changes

2023-06-03 00:36 UTC, merged